version: 2
jobs:
  build:
    docker:
      - image: cimg/node:18.12

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Run tests
          command: npm run test:js

      - run:
          name: Check lint
          command: npm run lint
          when: always

      - run:
          name: Check prettier
          command: npm run prettier:check
          when: always
